$doctors = array(
	array(
		"doctor_id" => 11,
		"name" => "sara bukhari",
		"email" => "sara@gmail.com",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$eklTNi5oU29EWUc5L3NSLw$KvD01yUP+mcSr7hI9EdHZVBytQxlmFLfW05szWJSOek",
		"phone_number" => "0554546124",
		"specialty" => "dentist",
		"experience_years" => 7,
		"location" => "jeddah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 13,
		"name" => "mohammed",
		"email" => "mohammed@gmail.com",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$cFM1WXBPMGFxam5BM3lBMw$y7MNY7m++E/XSYjkVAoZth0KzkbcE9AtoQILaxpMddg",
		"phone_number" => "0545568735",
		"specialty" => "Psychiatrist",
		"experience_years" => 5,
		"location" => "Jeddah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 14,
		"name" => "Amer Mohammad",
		"email" => "Amer@gmail.com",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$L2VJektUNy84ai9hMkRiNw$5i2ttLaaL5OkjDPtwOoCMhoQwsngA83j3gVfq3FWTdM",
		"phone_number" => "0507738814",
		"specialty" => "family physician",
		"experience_years" => 15,
		"location" => "makkah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => "6141a8da200669752dc270e20f9e7564ea7f72896606432960eb9dc62a5bbb41",
		"reset_token_expires_at" => "2025-04-13 03:03:09",
	),
	array(
		"doctor_id" => 16,
		"name" => "Alma ahmad",
		"email" => "AlmaAhmad@gmail.com",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$eUdKNUJ2dTJ5Y2d2QVZKaw$JNZYprqOnIHC5wO9midISV7P09MJueKzmQuovjjhe9I",
		"phone_number" => "0557757698",
		"specialty" => "dentist",
		"experience_years" => 25,
		"location" => "jeddah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 17,
		"name" => "Sarah Johnson",
		"email" => "sarah.johnson@hospital.com",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$ZVB6MDNrVjBjdktkRlNzTQ$NHcYX2gLoygplsN3EtuVm/Rn3dWfBlf+owsIlDoL7OY",
		"phone_number" => "0551234567",
		"specialty" => "family physician",
		"experience_years" => 12,
		"location" => "Riyadh",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 18,
		"name" => "Ahmed Al-Mutairi",
		"email" => "ahmed.mutairi@clinic.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$emZ3SFBOejZyNFAwbjJYdQ$4k5zHw3OpiGb1vs4+MQymBRg/E2pl0FRs5mrRA7wWiE",
		"phone_number" => "0554546188",
		"specialty" => "Dentist",
		"experience_years" => 8,
		"location" => "Jeddah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 19,
		"name" => "Layla Omar",
		"email" => "layla.omar@health.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$SGFhcC5aYms5VWVaNTFxRw$pGFb+MrR6k3pYbqRIPwQvca4RCn0xsSgdvRYjQtwhUM",
		"phone_number" => "0554546189",
		"specialty" => "Dermatologist",
		"experience_years" => 10,
		"location" => "Makkah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 20,
		"name" => "Khaled Ali",
		"email" => "khaled.ali@medic.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$YzMwSTdiVmJpQzFnWDN6NQ$ZLoCdVgOuwqd5EfZK+f9fx/967Lh3xSQJ7/+s2wz32c",
		"phone_number" => "0554546190",
		"specialty" => "Pediatrician",
		"experience_years" => 15,
		"location" => "Riyadh",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 21,
		"name" => "Dr. Hanan Saleh",
		"email" => "hanan.saleh@care.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$cFJld3FmbHVETTkuOVR2Tw$qEm6ekWaj5q1zgCPtaVcTcs2sT5xiFW+0Y7Ht71wvDA",
		"phone_number" => "0554546191",
		"specialty" => "Dermatologist",
		"experience_years" => 7,
		"location" => "Jeddah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 22,
		"name" => "Faisal Al-Harbi",
		"email" => "faisal.harbi@clinic.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$clc4Q0J1Qkd3UXNSMFlHbA$dYSUUDKHJkOKOqqxKkA5xcC9hi2rgocteKW+NXPG9Po",
		"phone_number" => "0554546192",
		"specialty" => "family physician",
		"experience_years" => 14,
		"location" => "Riyadh",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 23,
		"name" => "Mariam Zaki",
		"email" => "mariam.zaki@hospital.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$TXRwZnNiOC54WENxY1I4Sg$ke7hMSWb0MPaFkNzcqHpzT9+EiK6xmSp3Q6uJPnHYgA",
		"phone_number" => "0554546193",
		"specialty" => "family physician",
		"experience_years" => 9,
		"location" => "Jeddah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 24,
		"name" => "Omar Yousef",
		"email" => "omar.yousef@medic.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$RlFkWXlhblkyb28zS3Y1UA$muLNfROG74rW7GmmZtWT5WO2/vKLD9y5p0P4ReVi+CE",
		"phone_number" => "0554546194",
		"specialty" => "Psychiatrist",
		"experience_years" => 13,
		"location" => "makkah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 25,
		"name" => "Nadia Farouk",
		"email" => "nadia.farouk@clinic.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$aWtNZWcvbW8zbndHRlBkdw$aeLbtpyrmVwYCWwyOk20FH0kkvX6hZy6wW1NXTUx7mo",
		"phone_number" => "0554546195",
		"specialty" => "Psychiatrist",
		"experience_years" => 11,
		"location" => "Jeddah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 26,
		"name" => "Saeed Malik",
		"email" => "saeed.malik@hospital.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$Y1RVTW02NzBEdi9yVWIwdg$d/PRlJ/nAlMb/OV8C8mzCYN3HqP+xo2+00kGtrzDzRU",
		"phone_number" => "0554546196",
		"specialty" => "family physician",
		"experience_years" => 10,
		"location" => "Riyadh",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 27,
		"name" => "Yasmin Ahmed",
		"email" => "yasmin.ahmed@clinic.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$RlJmOW0uRTVZSk02QXpQaw$ljdo8UHVawFxVjqYSBTJ3p7lstTXkxVu/MPenPf0/jo",
		"phone_number" => "0554546197",
		"specialty" => "family physician",
		"experience_years" => 6,
		"location" => "Jeddah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 28,
		"name" => "Tariq Al-Farsi",
		"email" => "tariq.farsi@medic.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$MlhjdEc4RWd2ajJDNG9EdQ$QGRbg2L620+RGMHLUWbaq7ci7tNYTXT54kOY/L+zhPE",
		"phone_number" => "0554546198",
		"specialty" => "family physician",
		"experience_years" => 12,
		"location" => "Makkah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 29,
		"name" => "Aisha Noor",
		"email" => "aisha.noor@health.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$SE1nY2NWSURDakl6U3ZTaQ$3nMvvEQ8S2YIaa50p+0zT9OLjM0tN2H4bGyS7QUxCto",
		"phone_number" => "0554546199",
		"specialty" => "Psychiatrist",
		"experience_years" => 10,
		"location" => "Riyadh",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 30,
		"name" => "Hassan Ibrahim",
		"email" => "hassan.ibrahim@hospital.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$ZGlWaUhXdC5hUVY4YlpxSQ$D/tRb0SLgTbBGK1h1pKWvFwb1Ok0lxlz7UmPXNgUKuQ",
		"phone_number" => "0554546200",
		"specialty" => "Cardiologist",
		"experience_years" => 8,
		"location" => "makkah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 31,
		"name" => "Noor Hadi",
		"email" => "noor.hadi@medic.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$bU9CckRXc0RWY0tNdEV6Vw$uwccxKXfcA+WHzijcGGmbJ64oMvxwWBMmtWbwXSAqIE",
		"phone_number" => "0554546201",
		"specialty" => "Cardiologist",
		"experience_years" => 11,
		"location" => "makkah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 32,
		"name" => "Ibrahim Khalil",
		"email" => "ibrahim.khalil@clinic.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$VzM1UWp2QUhmeDVMbkV1Ug$vA2ZudXf4Moz39fvwDVRMMJ5OLp7L1G46/1kdwlcPOk",
		"phone_number" => "0554546202",
		"specialty" => "family physician",
		"experience_years" => 14,
		"location" => "Riyadh",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 33,
		"name" => "Salma Mansour",
		"email" => "salma.mansour@health.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$Z2h4ZDNxL29MV0t6T0xhOQ$OYziTpVPsAf1O19Za/oNPrJojMALAUOOaa16QUZfKww",
		"phone_number" => "0554546203",
		"specialty" => "Pediatrician",
		"experience_years" => 9,
		"location" => "Riyadh",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 34,
		"name" => "Jamal Rafiq",
		"email" => "jamal.rafiq@hospital.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$dnh3MnF5Y2s3ZXdFTlQzYw$XvP7V/4Jr5XLWFaSDFqSmSIyizDl+kj/6q2kzApjYYc",
		"phone_number" => "0554546204",
		"specialty" => "Pediatrician",
		"experience_years" => 13,
		"location" => "Riyadh",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 35,
		"name" => "Noura Al-Badr",
		"email" => "noura.badr@clinic.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$Nlp5WGNRd0g0eHk2V3pCYQ$F3N1E21M7W87Oi/BFg+1NdfXidSodAghnqVoPLQ6En8",
		"phone_number" => "0554546205",
		"specialty" => "Pediatrician",
		"experience_years" => 7,
		"location" => "Riyadh",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 36,
		"name" => "Zaid Al-Mashari",
		"email" => "zaid.mashari@medic.sa",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$bWtSZVF6UVhacExmdG4uTw$Pd8HHNSwrwTbULUqIQSb2h1vy1NjaVQZXkaUUc83j7g",
		"phone_number" => "0554546206",
		"specialty" => "Cardiologist",
		"experience_years" => 8,
		"location" => "Jeddah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 37,
		"name" => "John smith",
		"email" => "johnSmith@gmail.com",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$TnhJR25GR0tYV05WTkJQaA$5yK4pbKGHoG3Z03UrcfFJ+2rSa9Jd/U85SzVj4Pg8+U",
		"phone_number" => "0555028014",
		"specialty" => "Pediatrician",
		"experience_years" => 5,
		"location" => "makkah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 101,
		"name" => "omar mahmood",
		"email" => "omar@gmail.com",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$eGd0L09LZm00M3Fnck1XRg$RoE6eh+JEnMVmZ/pxsRrvBH+mSV9b48geGy8Ef6GB8A",
		"phone_number" => "0578994458",
		"specialty" => "dentist",
		"experience_years" => 5,
		"location" => "Jeddah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 112,
		"name" => "shorog ali",
		"email" => "shorog12@gmail.com",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$cEhkcG9RWFB2MU1ONHNIZA$U+MbhlSP//3ps15bNab4eerGX33FhTmbYfHLt/LK//4",
		"phone_number" => "0503038714",
		"specialty" => "dentist",
		"experience_years" => 3,
		"location" => "Jeddah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 113,
		"name" => "Adam Reynolds",
		"email" => "adam.reynolds@gmail.com",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$U2lsdjBQSnltdzBHcEFqTQ$Z83H2om3uBdNxfU6PrhsF0ZLaiVUKL7e52UwKgvDYFc",
		"phone_number" => "0553038704",
		"specialty" => "dentist",
		"experience_years" => 5,
		"location" => "Jeddah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 114,
		"name" => "Sarah Mitchell",
		"email" => "sarah.mitchell@gmail.com",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$d3lXVE5OcFVSNTlRWkRraQ$kFRI5bKDl5vmyMB7OP+Or+oJuBc3uCCQT/6EtMav65k",
		"phone_number" => "0505568035",
		"specialty" => "dentist",
		"experience_years" => 7,
		"location" => "Jeddah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 115,
		"name" => "Omar Al-Farsi",
		"email" => "omar.alfarsi@example.com",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$S1JNYnhDYmxuV3A4ZnQ3Tw$dxlim+PzKe0wJIPumQMtZTG/8ucVNW2wH9wsrYhKKaE",
		"phone_number" => "0535068730",
		"specialty" => "dentist",
		"experience_years" => 6,
		"location" => "Jeddah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 116,
		"name" => "Ahmed Bukhari",
		"email" => "ahmed.Bukhari@gmail.com",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$OHlSQThhNjVPWXFWaE5YWQ$lYhvYHdDFv9z0vtOd1NJe2IQ2YXRRKrL95iz9H/Sbto",
		"phone_number" => "0517028714",
		"specialty" => "dentist",
		"experience_years" => 6,
		"location" => "Jeddah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => NULL,
		"reset_token_expires_at" => NULL,
	),
	array(
		"doctor_id" => 122,
		"name" => "Azizah Bukhari",
		"email" => "Azizah@gmail.com",
		"password" => "$argon2id$v=19$m=65536,t=4,p=1$TE1sQjE1ZmxsbTN4S2xocQ$vVm6LNrlmW+RlXC2jlbwBYx0qMzQzHAZRKZg57yUkg4",
		"phone_number" => "0554543987",
		"specialty" => "Pediatrician",
		"experience_years" => 10,
		"location" => "Makkah",
		"admin_approval" => "yes",
		"active" => "yes",
		"active_hospital" => "yes",
		"reset_token_hash" => "2cbf8effe37d23635fb7403794895185cabe26e6931af7997a7e4b52bd6f7092",
		"reset_token_expires_at" => "2025-04-07 21:41:11",
	),
);
